import Footer from "@/components/Global/Footer";
import Header from "@/components/Global/Header";
import Hero from "@/components/Home/Hero";
import Projects from "@/components/Home/Projects";
import Services from "@/components/Home/Services";
import Head from "next/head";
import { quicksand, poppins } from "@/utils/fonts";

export default function Home() {
  return (
    <>
      <Head>
        <title>Beatriz Moreira | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`scroll-smooth px-10 sm:px-5 md:px-4 w-full grid grid-cols-mainLayout gap-x-4 justify-center pb-24 md:pb-32 ${quicksand.variable} ${poppins.variable}
        
        `}
      >
        <Header />
        <Hero />
        <Projects />
        <Services />
        <Footer />
      </div>
    </>
  );
}
